name: Deploy Lambda

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_my_ip: ${{ secrets.MY_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4  
        with:
          terraform_version: 1.5.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Terraform Apply - Create infrastructure
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -target=module.vpc \
            -target=aws_s3_bucket.crypto_bucket \
            -target=aws_security_group.rds_sg \
            -target=aws_db_subnet_group.crypto_subnets \
            -target=aws_db_instance.crypto_db \
            -target=aws_iam_role.lambda_exec \
            -target=aws_iam_role_policy_attachment.lambda_basic \
            -target=aws_iam_role_policy_attachment.lambda_vpc \
            -target=aws_iam_role_policy.lambda_s3 \
            -target=aws_security_group.lambda_sg  
        
      - name: Install dependencies
        run: |
          pip install requests PyMySQL --target ./package
          cp src/*.py package/
          cp src/global-bundle.pem package/

      - name: Create zip
        run: |
          cd package
          zip -r ../lambda_package.zip .

      - name: Upload zip to S3
        run: |
          aws s3 cp lambda_package.zip s3://crypto-pipeline-gui/lambda/lambda_package.zip

      - name: Terraform Apply - Create Lambda Function
        run: |
          cd terraform
          terraform apply -auto-approve \
            -target=aws_lambda_function.crypto_pipeline
      